name: toporet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.5
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - keras=2.10.0
  - tensorflow=2.10.0
  - pip
  - pip:
      - timm
      - pandas
      - scikit-learn
